"""Generate a KiCad `.kicad_dru` that enforces HV creepage HONESTLY.

The problem (see the project's creepage memo): a KiCad net-class `clearance` is
a blanket pad-to-pad rule. Give the HV classes their real creepage values and
KiCad flags every HV component's OWN pads — a resistor's two terminals are
~0.6 mm apart and can never hold 2-7 mm between them. On Voxy region 1 that was
214 of 225 pad-pad "violations": unfixable by any placement or router.

Creepage is a rule between DISTINCT high-voltage NODES separated across the
board surface — not between the two terminals of one part (that gap is the
component's own voltage rating). This tool emits custom DRC rules that say
exactly that, using predicates verified against kicad-cli (KiCad 10):

  - `A.Parent == B.Parent`  → same footprint (intra-component). EXEMPT.
    (`A.memberOfFootprint(B)` and `A.Footprint == B.Footprint` do NOT work.)
  - `A.Net != B.Net`        → different nets (a real node pair).

Two rule flavours, pick by how the net classes are set:

  intra-exempt (default): keep the HV net-class `clearance` at the creepage
    value (so Orchard's router keeps spacing HV copper by it), and add ONE rule
    that exempts same-footprint pairs. KiCad then stops reporting the 214
    impossible intra-component violations; real node-to-node creepage still
    checks via the net class. Minimal, no router change.

  --explicit (for when the net-class clearances are normalised back to a
    fab value like 0.2 mm): emit a per-class rule that re-adds creepage ONLY
    between distinct HV nodes of the same class. Use this if you also want
    KiCad to stop flagging HV-copper-vs-logic-pad as a creepage miss.

Usage:
  python scripts/creepage_rules.py PROJECT.kicad_pro [--out rules.kicad_dru]
        [--explicit] [--min-hv-clearance 1.0]
"""
import json
import sys


def load_classes(pro_path):
    """{class_name: clearance_mm} from a .kicad_pro's net_settings.classes.
    A class with no explicit clearance is skipped (it inherits Default and
    carries no creepage intent of its own)."""
    with open(pro_path, encoding="utf-8") as f:
        pro = json.load(f)
    out = {}
    for c in (pro.get("net_settings", {}) or {}).get("classes", []) or []:
        name = c.get("name")
        if name is not None and c.get("clearance") is not None:
            out[name] = float(c["clearance"])
    return out


def hv_classes(classes, min_hv_clearance):
    """The classes whose clearance is a creepage value: named HV* or wider than
    the threshold. Returned name->mm, widest first (documentation order)."""
    hv = {n: mm for n, mm in classes.items()
          if n.upper().startswith("HV") or mm >= min_hv_clearance}
    return dict(sorted(hv.items(), key=lambda kv: -kv[1]))


def _esc(name):
    """A class/net name inside a KiCad expression string literal. Names with a
    single quote would break the literal; KiCad has no escape, so flag it."""
    if "'" in name:
        raise ValueError(f"class name {name!r} contains a quote — KiCad DRC "
                         f"expressions cannot quote it; rename the class")
    return name


def generate_dru(classes, explicit=False, min_hv_clearance=1.0):
    """Return `.kicad_dru` text. Always emits the intra-component exemption;
    with explicit=True also emits per-HV-class node-to-node creepage rules."""
    hv = hv_classes(classes, min_hv_clearance)
    lines = ["(version 1)", "",
             "# Generated by Orchard Route creepage_rules.py.",
             "# Creepage is between DISTINCT HV NODES, not a component's own pads.", ""]
    if not hv:
        lines.append("# (no HV/creepage classes found in the project)")
        return "\n".join(lines) + "\n"

    # Intra-component exemption: a part's own pad pitch is fixed by the part and
    # is the component's voltage rating, not a PCB creepage rule. Scoped to the
    # HV classes so ordinary parts are untouched.
    cond = " || ".join(f"A.NetClass == '{_esc(n)}'" for n in hv)
    lines += [
        '(rule "creepage_intra_component_exempt"',
        "  # a footprint's two terminals cannot be spread by place or route",
        f'  (condition "(A.Parent == B.Parent) && ({cond})")',
        "  (constraint clearance (min 0mm)))",
        "",
    ]
    if explicit:
        lines += [
            "# Net-class clearances are assumed normalised to a fab value; these",
            "# re-add creepage ONLY between distinct nodes of the same HV class.",
            "",
        ]
        for name, mm in hv.items():
            n = _esc(name)
            lines += [
                f'(rule "creepage_{n}"',
                f'  (condition "A.NetClass == \'{n}\' && B.NetClass == \'{n}\' '
                f'&& A.Net != B.Net && A.Parent != B.Parent")',
                f"  (constraint clearance (min {mm}mm)))",
                "",
            ]
    return "\n".join(lines) + "\n"


def main(argv):
    explicit = "--explicit" in argv
    argv = [a for a in argv if a != "--explicit"]
    out_path, min_hv, rest, i = None, 1.0, [], 0
    while i < len(argv):
        if argv[i] == "--out":
            out_path = argv[i + 1]; i += 2
        elif argv[i] == "--min-hv-clearance":
            min_hv = float(argv[i + 1]); i += 2
        else:
            rest.append(argv[i]); i += 1
    if not rest:
        print(__doc__)
        return 2
    classes = load_classes(rest[0])
    text = generate_dru(classes, explicit=explicit, min_hv_clearance=min_hv)
    if out_path:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(text)
        hv = hv_classes(classes, min_hv)
        print(f"wrote {out_path} — HV classes: "
              f"{', '.join(f'{n} {mm}mm' for n, mm in hv.items()) or 'none'}"
              f"{' (explicit per-class rules)' if explicit else ' (intra-exempt only)'}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
